# Generated by Django 4.0.7 on 2023-08-04 12:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fa_title', models.CharField(max_length=255)),
                ('en_title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('learning', 'Learning'), ('working', 'Working'), ('developing', 'Developing'), ('reading', 'Reading'), ('watching', 'Watching'), ('writing', 'Writing')], default='learning', max_length=110)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fa_title', models.CharField(max_length=255)),
                ('en_title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=355, null=True)),
                ('is_holiday', models.BooleanField(default=True)),
                ('spend_time', models.IntegerField(verbose_name='spend_time(minute)')),
                ('activity_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activityitem')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planing.plan')),
                ('plan_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planing.plandetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activityitem',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.topics'),
        ),
    ]
