# Generated by Django 4.0.7 on 2023-08-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityitem',
            name='source_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
