# Generated by Django 4.0.7 on 2023-08-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activityitem_github_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityitem',
            old_name='github_source',
            new_name='git_source',
        ),
    ]
