# Generated by Django 4.0.7 on 2023-08-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_remove_activitylog_spend_time_activitylog_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
