# Generated by Django 4.0.7 on 2023-08-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0006_remove_plan_purpose_remove_purpose_comment_and_more'),
        ('users', '0003_baseuser_first_name_baseuser_last_name_and_more'),
        ('activity', '0008_alter_activitylog_is_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityitem',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planing.purpose'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='base_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.baseuser'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planing.purpose'),
        ),
    ]
