# Generated by Django 4.0.7 on 2023-08-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_activityitem_purpose_activitylog_base_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='activity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
