# Generated by Django 4.0.7 on 2023-08-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_activitylog_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
