# Generated by Django 4.0.7 on 2023-08-15 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_alter_activitylog_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
