# Generated by Django 4.0.7 on 2023-09-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_alter_activitylog_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
