# Generated by Django 4.0.7 on 2023-09-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_activitylog_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
