# Generated by Django 4.0.7 on 2023-09-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_alter_activitylog_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
