# Generated by Django 4.0.7 on 2023-09-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_activitylog_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='detail',
            field=models.TextField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='comment',
            field=models.TextField(blank=True, max_length=555, null=True),
        ),
    ]
