# Generated by Django 4.0.7 on 2023-09-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_activitylog_detail_alter_activitylog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='comment',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
