# Generated by Django 4.0.7 on 2023-09-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_alter_activitylog_comment_alter_activitylog_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='comment',
            field=models.TextField(blank=True, max_length=555, null=True),
        ),
    ]
