# Generated by Django 4.0.7 on 2023-09-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_activitysource_activitylog_activity_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysource',
            name='domain',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
