# Generated by Django 4.0.7 on 2023-10-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0008_plan_rate'),
        ('activity', '0020_activitysource_domain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityItem',
            new_name='Item',
        ),
    ]
