# Generated by Django 4.0.7 on 2023-10-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0021_rename_activityitem_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivitySource',
            new_name='Source',
        ),
    ]
