# Generated by Django 4.0.7 on 2023-10-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0023_course_teacher_activitylog_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
