# Generated by Django 4.0.7 on 2023-10-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0025_creator_rename_course_learningresource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='created_resources_creators',
            field=models.ManyToManyField(related_name='creatorss', to='activity.learningresource'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='creators',
            field=models.ManyToManyField(related_name='learning_resources', to='activity.creator'),
        ),
    ]
