# Generated by Django 4.0.7 on 2023-10-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0027_alter_creator_created_resources_creators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='created_resources_creators',
            field=models.ManyToManyField(blank=True, null=True, related_name='creator', to='activity.learningresource'),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='creators',
            field=models.ManyToManyField(blank=True, null=True, related_name='learning_resource', to='activity.creator'),
        ),
    ]
