# Generated by Django 4.0.7 on 2023-10-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0028_alter_creator_created_resources_creators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.creator'),
        ),
    ]
