# Generated by Django 4.0.7 on 2023-10-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0030_remove_learningresource_creators'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='creators',
            field=models.ManyToManyField(blank=True, null=True, related_name='learning_resource', to='activity.creator'),
        ),
    ]
