# Generated by Django 4.0.7 on 2023-10-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0032_creator_github_address_creator_website_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='linkedin_address',
            field=models.URLField(blank=True, null=True),
        ),
    ]
