# Generated by Django 4.0.7 on 2023-10-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0034_creator_telegram_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
