# Generated by Django 4.0.7 on 2023-10-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0036_creator_email_address_creator_instagram_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='twitter',
            new_name='twitter_address',
        ),
    ]
