# Generated by Django 4.0.7 on 2023-10-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0039_rename_created_resources_creators_creator_created_resources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='created_resources',
            new_name='created_resources_creators',
        ),
    ]
