# Generated by Django 4.0.7 on 2023-11-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0040_rename_created_resources_creator_created_resources_creators'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
