# Generated by Django 4.0.7 on 2024-02-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0041_creator_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity.creator'),
        ),
    ]
