# Generated by Django 4.0.7 on 2023-08-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0002_topic_remove_plandetail_title_plandetail_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetail',
            name='description',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
