# Generated by Django 4.0.7 on 2023-08-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0003_plandetail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetail',
            name='unit_of_measure',
            field=models.CharField(choices=[('page', 'صفحه'), ('minute', 'دقیقه')], default='minute', max_length=75),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='effort_amount_per_day',
            field=models.IntegerField(),
        ),
    ]
