# Generated by Django 4.0.7 on 2023-08-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0004_plandetail_unit_of_measure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetail',
            name='total_time_spent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
