# Generated by Django 4.0.7 on 2023-08-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0005_plandetail_total_time_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='purpose',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='purpose',
            name='year',
        ),
        migrations.AddField(
            model_name='plan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plandetail',
            name='puprpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planing.purpose'),
        ),
        migrations.AddField(
            model_name='purpose',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purpose',
            name='started_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purpose',
            name='unit_of_measure',
            field=models.CharField(choices=[('page', 'صفحه'), ('minute', 'دقیقه')], default='minute', max_length=75),
        ),
    ]
