# Generated by Django 4.0.7 on 2023-09-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0006_remove_plan_purpose_remove_purpose_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plandetail',
            name='is_hiden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plandetail',
            name='was_delete',
            field=models.BooleanField(default=False),
        ),
    ]
