# Generated by Django 4.0.7 on 2023-09-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0007_plan_feedback_plandetail_is_hiden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
