# Generated by Django 4.0.7 on 2023-11-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planing', '0008_plan_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='was_delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='was_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
